### ISSUE TITLE
@types/lru-cache deprecated

### ISSUE THREAD

**Issue by mbrinkl** [delucis/bgio-storage-cache#311]
Was going to put in a PR, but removing this also requires upgrading lru-cache, which dependabot already has a PR in for.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/16028371/200088349-a3ec3df6-2827-41d3-979a-3f672d6d7e9e.png">

**Comment by delucis** [comment]
PR would be great! We can always close the dependabot ones.
